"""Rung 2 - truth with the three structural coefficients perturbed x1.15.

RATIONALE (rung 1 -> 2): a fixed 15% proportional error on assignment strength,
dose effect and severity effect produces a small but systematic mismatch in
EVERY regime - in-support, off-support and observational alike. Expected
strictly below the exact truth (whose only mismatch is sampling noise) and
strictly above rungs that break structure rather than calibration.

GENERATED by make_ladder_fixtures.py (POOL_SEED=20260611, POOL_N=20000) - do not
hand-edit; regenerate to audit. If an ordering fails, the default is to
INVESTIGATE, never to retune (Decision Log v0.11).
"""
import numpy as np
import pandas as pd

SEV_COEF_DOSE = 1.7249999999999999
DOSE_BASE = 2.0
DOSE_NOISE = 1.0
EFFECT_DOSE = 1.15
EFFECT_SEV = -2.3
OUTCOME_NOISE = 0.5
MARKER_NOISE = 1.5


def _saturating(dose):
    return 10.0 * dose / (dose + 4.0)


def model(regime, n, seed):
    rng = np.random.default_rng(seed)
    cohort = regime.context.get("cohort", 0.0)
    severity = rng.normal(cohort, 1.0, n)
    if "dose" in regime.config:
        dose = np.full(n, float(regime.config["dose"]))
    else:
        raw = DOSE_BASE + SEV_COEF_DOSE * severity + rng.normal(0.0, DOSE_NOISE, n)
        dose = np.clip(raw, 0.0, 10.0)
    outcome = (
        EFFECT_DOSE * _saturating(dose)
        + EFFECT_SEV * severity
        + rng.normal(0.0, OUTCOME_NOISE, n)
    )
    marker = severity + rng.normal(0.0, MARKER_NOISE, n)
    return pd.DataFrame({"dose": dose, "marker": marker, "outcome": outcome})
