"""Rung 5 - naive generative fit: joint gaussian of the corrupted pool.

This is rival recipe (a): "the data says what it seems to say". A flexible
generative fit to the observational pool, used generatively: under do(dose) it
samples (marker, outcome) from the OBSERVATIONAL conditional given that dose.

RATIONALE (rung 4 -> 5): this rung drags every spurious correlation of the
pool into regimes where randomization breaks them - under do(dose=high) it
still predicts severe markers (the indication pattern), which is exactly what
intervention falsifies. The innocent twin at least generates exogenous
conditions correctly (marker independent of dose under do()); it is wrong
only in the causal coefficient. Both ignore context shifts.

GENERATED by make_ladder_fixtures.py (POOL_SEED=20260611, POOL_N=20000) - do not
hand-edit; regenerate to audit. If an ordering fails, the default is to
INVESTIGATE, never to retune (Decision Log v0.11).
"""
import numpy as np
import pandas as pd

MU = np.array([2.12029074426587, -0.010066254938579055, 3.026598896300007])
COV = np.array([[2.5671223339566716, 1.3231933413834258, 0.15714183209646276], [1.3231933413834258, 3.2617256582792766, -0.5578501608634212], [0.15714183209646276, -0.5578501608634212, 1.673714556709191]])


def model(regime, n, seed):
    rng = np.random.default_rng(seed)
    if "dose" in regime.config:
        d = float(regime.config["dose"])
        mu_cond = MU[1:] + COV[1:, 0] / COV[0, 0] * (d - MU[0])
        cov_cond = COV[1:, 1:] - np.outer(COV[1:, 0], COV[0, 1:]) / COV[0, 0]
        draw = rng.multivariate_normal(mu_cond, cov_cond, n)
        dose = np.full(n, d)
        marker = draw[:, 0]
        outcome = draw[:, 1]
    else:
        draw = rng.multivariate_normal(MU, COV, n)
        dose = np.clip(draw[:, 0], 0.0, 10.0)
        marker = draw[:, 1]
        outcome = draw[:, 2]
    return pd.DataFrame({"dose": dose, "marker": marker, "outcome": outcome})
