"""Rung 4 - innocent twin: the confounding-by-indication operator removed.

This is rival recipe (b): the mechanistic skeleton of the truth with the trap
removed and parameters re-fitted to the corrupted observational pool. It
believes the observational dose-outcome association IS causal: no latent
severity anywhere, so the dose coefficient absorbs the confounding bias.

RATIONALE (rung 3 -> 4): rung 3 has the CORRECT causal coefficients and only a
degraded functional form - it is wrong only where curvature matters. This rung
has the WRONG causal effect (biased by indication) plus no severity pathway:
it mispredicts outcome in EVERY do(dose) regime, including mid in-support
where the battery mass sits, and is blind to cohort context shifts.

GENERATED by make_ladder_fixtures.py (POOL_SEED=20260611, POOL_N=20000) - do not
hand-edit; regenerate to audit. If an ordering fails, the default is to
INVESTIGATE, never to retune (Decision Log v0.11).
"""
import numpy as np
import pandas as pd

BETA0 = 2.72883264758897
BETA1 = 0.09898310448667
RESID_SD = 1.2812637147708887
MU_DOSE = 2.1202907442658643
SD_DOSE = 1.6021841273211934
MU_MARKER = -0.01006625493857902
SD_MARKER = 1.8059796709809228


def _saturating(dose):
    return 10.0 * dose / (dose + 4.0)


def model(regime, n, seed):
    rng = np.random.default_rng(seed)
    if "dose" in regime.config:
        dose = np.full(n, float(regime.config["dose"]))
    else:
        dose = np.clip(rng.normal(MU_DOSE, SD_DOSE, n), 0.0, 10.0)
    outcome = BETA0 + BETA1 * _saturating(dose) + rng.normal(0.0, RESID_SD, n)
    marker = rng.normal(MU_MARKER, SD_MARKER, n)
    return pd.DataFrame({"dose": dose, "marker": marker, "outcome": outcome})
