"""Rung 6 - null model: independent marginals of the observational pool.

RATIONALE (rung 5 -> 6): the null keeps only the historical marginals - it
destroys every dependency between columns AND every sensitivity to the regime
(under do(dose) it still samples dose from the pool marginal: the implicit
no-effect claim, priced by the battery on every item). Any fit to real data
beats it on joint structure; it is the calibrated "I know nothing" floor that
anchors the L1 range (S_truth - S_null) and the D_MAX cap semantics.

GENERATED by make_ladder_fixtures.py (POOL_SEED=20260611, POOL_N=20000) - do not
hand-edit; regenerate to audit. If an ordering fails, the default is to
INVESTIGATE, never to retune (Decision Log v0.11).
"""
import numpy as np
import pandas as pd

MU_DOSE = 2.1202907442658643
SD_DOSE = 1.6021841273211934
MU_MARKER = -0.01006625493857902
SD_MARKER = 1.8059796709809228
MU_OUTCOME = 3.026598896299985
SD_OUTCOME = 1.293688861736606


def model(regime, n, seed):
    rng = np.random.default_rng(seed)
    dose = np.clip(rng.normal(MU_DOSE, SD_DOSE, n), 0.0, 10.0)
    marker = rng.normal(MU_MARKER, SD_MARKER, n)
    outcome = rng.normal(MU_OUTCOME, SD_OUTCOME, n)
    return pd.DataFrame({"dose": dose, "marker": marker, "outcome": outcome})
