"""Rung 3 - truth with the saturation linearized (mechanism ablated).

RATIONALE (rung 2 -> 3): this rung keeps the full causal structure (confounded
assignment, severity effect) but replaces sat(d) with the straight line fitted
on the historical dose support. It is nearly exact where the line tracks the
curve (mid in-support) but diverges SYSTEMATICALLY where curvature matters:
high off-support doses (the line keeps climbing while the truth saturates) and
dose=0 (nonzero intercept where the truth passes through the origin). The
battery prices both regions. Rung 2 is uniformly close everywhere; this rung
is structurally wrong in weighted regions - hence the expected gap.

GENERATED by make_ladder_fixtures.py (POOL_SEED=20260611, POOL_N=20000) - do not
hand-edit; regenerate to audit. If an ordering fails, the default is to
INVESTIGATE, never to retune (Decision Log v0.11).
"""
import numpy as np
import pandas as pd

SEV_COEF_DOSE = 1.5
DOSE_BASE = 2.0
DOSE_NOISE = 1.0
SAT_SLOPE = 1.0874675836203673
SAT_INTERCEPT = 0.7025058275020094
EFFECT_DOSE = 1.0
EFFECT_SEV = -2.0
OUTCOME_NOISE = 0.5
MARKER_NOISE = 1.5


def _linear_response(dose):
    return SAT_SLOPE * dose + SAT_INTERCEPT


def model(regime, n, seed):
    rng = np.random.default_rng(seed)
    cohort = regime.context.get("cohort", 0.0)
    severity = rng.normal(cohort, 1.0, n)
    if "dose" in regime.config:
        dose = np.full(n, float(regime.config["dose"]))
    else:
        raw = DOSE_BASE + SEV_COEF_DOSE * severity + rng.normal(0.0, DOSE_NOISE, n)
        dose = np.clip(raw, 0.0, 10.0)
    outcome = (
        EFFECT_DOSE * _linear_response(dose)
        + EFFECT_SEV * severity
        + rng.normal(0.0, OUTCOME_NOISE, n)
    )
    marker = severity + rng.normal(0.0, MARKER_NOISE, n)
    return pd.DataFrame({"dose": dose, "marker": marker, "outcome": outcome})
