"""Deterministic generator of the dummy_dose_v0 ladder fixtures (rungs 2-6).

Factory-side tooling (bootstrap exception, Decision Log v0.10: hand-built
ladder is Slice-1-only and expires with automatic rival derivation).

Everything is derived from a FIXED observational pool (POOL_SEED) drawn from
the true world: re-running this script must reproduce the committed fixtures
byte-for-byte. Fits are closed-form OLS / moments - no optimizer randomness.

It also calibrates the provisional lambda (Decision Log v0.11): lambda such
that the MDL term of world.py equals 5% of the FIDELITY range
(fid_truth - fid_null) on the production battery, and writes it to meta.json.

Run:  .venv/Scripts/python cases/dummy_dose_v0/make_ladder_fixtures.py
"""

import json
from pathlib import Path
from types import SimpleNamespace

import numpy as np

CASE_DIR = Path(__file__).parent
POOL_SEED = 20260611
POOL_N = 20000
PERTURB = 1.15  # fixed multiplier on the three structural coefficients (rung 2)


def observational_pool():
    from wager.factory.case_loader import load_world_sample

    sample = load_world_sample(CASE_DIR)
    regime = SimpleNamespace(config={}, context={"cohort": 0.0}, horizon=None)
    return sample(regime, POOL_N, POOL_SEED)


def saturating(dose):
    return 10.0 * dose / (dose + 4.0)


def fit_numbers(pool):
    dose = pool["dose"].to_numpy()
    marker = pool["marker"].to_numpy()
    outcome = pool["outcome"].to_numpy()

    # rung 3: straight line fitted to sat(d) over the historical dose support
    sat_slope, sat_intercept = np.polyfit(dose, saturating(dose), 1)

    # rung 4: OLS outcome ~ sat(dose) on the corrupted pool (the naive causal read)
    x = np.column_stack([np.ones_like(dose), saturating(dose)])
    beta, *_ = np.linalg.lstsq(x, outcome, rcond=None)
    resid_sd = float(np.std(outcome - x @ beta))

    # rung 5: joint gaussian moments of the pool
    data = np.column_stack([dose, marker, outcome])
    mu = data.mean(axis=0)
    cov = np.cov(data, rowvar=False)

    return {
        "sat_slope": float(sat_slope),
        "sat_intercept": float(sat_intercept),
        "beta0": float(beta[0]),
        "beta1": float(beta[1]),
        "resid_sd": resid_sd,
        "mu_dose": float(dose.mean()),
        "sd_dose": float(dose.std()),
        "mu_marker": float(marker.mean()),
        "sd_marker": float(marker.std()),
        "mu_outcome": float(outcome.mean()),
        "sd_outcome": float(outcome.std()),
        "mu": [float(v) for v in mu],
        "cov": [[float(v) for v in row] for row in cov],
    }


HEADER = (
    "GENERATED by make_ladder_fixtures.py (POOL_SEED={seed}, POOL_N={n}) - do not\n"
    "hand-edit; regenerate to audit. If an ordering fails, the default is to\n"
    "INVESTIGATE, never to retune (Decision Log v0.11)."
)


def rung_2(f):
    header = HEADER.format(seed=POOL_SEED, n=POOL_N)
    return f'''"""Rung 2 - truth with the three structural coefficients perturbed x{PERTURB}.

RATIONALE (rung 1 -> 2): a fixed 15% proportional error on assignment strength,
dose effect and severity effect produces a small but systematic mismatch in
EVERY regime - in-support, off-support and observational alike. Expected
strictly below the exact truth (whose only mismatch is sampling noise) and
strictly above rungs that break structure rather than calibration.

{header}
"""
import numpy as np
import pandas as pd

SEV_COEF_DOSE = {1.5 * PERTURB!r}
DOSE_BASE = 2.0
DOSE_NOISE = 1.0
EFFECT_DOSE = {1.0 * PERTURB!r}
EFFECT_SEV = {-2.0 * PERTURB!r}
OUTCOME_NOISE = 0.5
MARKER_NOISE = 1.5


def _saturating(dose):
    return 10.0 * dose / (dose + 4.0)


def model(regime, n, seed):
    rng = np.random.default_rng(seed)
    cohort = regime.context.get("cohort", 0.0)
    severity = rng.normal(cohort, 1.0, n)
    if "dose" in regime.config:
        dose = np.full(n, float(regime.config["dose"]))
    else:
        raw = DOSE_BASE + SEV_COEF_DOSE * severity + rng.normal(0.0, DOSE_NOISE, n)
        dose = np.clip(raw, 0.0, 10.0)
    outcome = (
        EFFECT_DOSE * _saturating(dose)
        + EFFECT_SEV * severity
        + rng.normal(0.0, OUTCOME_NOISE, n)
    )
    marker = severity + rng.normal(0.0, MARKER_NOISE, n)
    return pd.DataFrame({{"dose": dose, "marker": marker, "outcome": outcome}})
'''


def rung_3(f):
    header = HEADER.format(seed=POOL_SEED, n=POOL_N)
    return f'''"""Rung 3 - truth with the saturation linearized (mechanism ablated).

RATIONALE (rung 2 -> 3): this rung keeps the full causal structure (confounded
assignment, severity effect) but replaces sat(d) with the straight line fitted
on the historical dose support. It is nearly exact where the line tracks the
curve (mid in-support) but diverges SYSTEMATICALLY where curvature matters:
high off-support doses (the line keeps climbing while the truth saturates) and
dose=0 (nonzero intercept where the truth passes through the origin). The
battery prices both regions. Rung 2 is uniformly close everywhere; this rung
is structurally wrong in weighted regions - hence the expected gap.

{header}
"""
import numpy as np
import pandas as pd

SEV_COEF_DOSE = 1.5
DOSE_BASE = 2.0
DOSE_NOISE = 1.0
SAT_SLOPE = {f["sat_slope"]!r}
SAT_INTERCEPT = {f["sat_intercept"]!r}
EFFECT_DOSE = 1.0
EFFECT_SEV = -2.0
OUTCOME_NOISE = 0.5
MARKER_NOISE = 1.5


def _linear_response(dose):
    return SAT_SLOPE * dose + SAT_INTERCEPT


def model(regime, n, seed):
    rng = np.random.default_rng(seed)
    cohort = regime.context.get("cohort", 0.0)
    severity = rng.normal(cohort, 1.0, n)
    if "dose" in regime.config:
        dose = np.full(n, float(regime.config["dose"]))
    else:
        raw = DOSE_BASE + SEV_COEF_DOSE * severity + rng.normal(0.0, DOSE_NOISE, n)
        dose = np.clip(raw, 0.0, 10.0)
    outcome = (
        EFFECT_DOSE * _linear_response(dose)
        + EFFECT_SEV * severity
        + rng.normal(0.0, OUTCOME_NOISE, n)
    )
    marker = severity + rng.normal(0.0, MARKER_NOISE, n)
    return pd.DataFrame({{"dose": dose, "marker": marker, "outcome": outcome}})
'''


def rung_4(f):
    header = HEADER.format(seed=POOL_SEED, n=POOL_N)
    return f'''"""Rung 4 - innocent twin: the confounding-by-indication operator removed.

This is rival recipe (b): the mechanistic skeleton of the truth with the trap
removed and parameters re-fitted to the corrupted observational pool. It
believes the observational dose-outcome association IS causal: no latent
severity anywhere, so the dose coefficient absorbs the confounding bias.

RATIONALE (rung 3 -> 4): rung 3 has the CORRECT causal coefficients and only a
degraded functional form - it is wrong only where curvature matters. This rung
has the WRONG causal effect (biased by indication) plus no severity pathway:
it mispredicts outcome in EVERY do(dose) regime, including mid in-support
where the battery mass sits, and is blind to cohort context shifts.

{header}
"""
import numpy as np
import pandas as pd

BETA0 = {f["beta0"]!r}
BETA1 = {f["beta1"]!r}
RESID_SD = {f["resid_sd"]!r}
MU_DOSE = {f["mu_dose"]!r}
SD_DOSE = {f["sd_dose"]!r}
MU_MARKER = {f["mu_marker"]!r}
SD_MARKER = {f["sd_marker"]!r}


def _saturating(dose):
    return 10.0 * dose / (dose + 4.0)


def model(regime, n, seed):
    rng = np.random.default_rng(seed)
    if "dose" in regime.config:
        dose = np.full(n, float(regime.config["dose"]))
    else:
        dose = np.clip(rng.normal(MU_DOSE, SD_DOSE, n), 0.0, 10.0)
    outcome = BETA0 + BETA1 * _saturating(dose) + rng.normal(0.0, RESID_SD, n)
    marker = rng.normal(MU_MARKER, SD_MARKER, n)
    return pd.DataFrame({{"dose": dose, "marker": marker, "outcome": outcome}})
'''


def rung_5(f):
    header = HEADER.format(seed=POOL_SEED, n=POOL_N)
    return f'''"""Rung 5 - naive generative fit: joint gaussian of the corrupted pool.

This is rival recipe (a): "the data says what it seems to say". A flexible
generative fit to the observational pool, used generatively: under do(dose) it
samples (marker, outcome) from the OBSERVATIONAL conditional given that dose.

RATIONALE (rung 4 -> 5): this rung drags every spurious correlation of the
pool into regimes where randomization breaks them - under do(dose=high) it
still predicts severe markers (the indication pattern), which is exactly what
intervention falsifies. The innocent twin at least generates exogenous
conditions correctly (marker independent of dose under do()); it is wrong
only in the causal coefficient. Both ignore context shifts.

{header}
"""
import numpy as np
import pandas as pd

MU = np.array({f["mu"]!r})
COV = np.array({f["cov"]!r})


def model(regime, n, seed):
    rng = np.random.default_rng(seed)
    if "dose" in regime.config:
        d = float(regime.config["dose"])
        mu_cond = MU[1:] + COV[1:, 0] / COV[0, 0] * (d - MU[0])
        cov_cond = COV[1:, 1:] - np.outer(COV[1:, 0], COV[0, 1:]) / COV[0, 0]
        draw = rng.multivariate_normal(mu_cond, cov_cond, n)
        dose = np.full(n, d)
        marker = draw[:, 0]
        outcome = draw[:, 1]
    else:
        draw = rng.multivariate_normal(MU, COV, n)
        dose = np.clip(draw[:, 0], 0.0, 10.0)
        marker = draw[:, 1]
        outcome = draw[:, 2]
    return pd.DataFrame({{"dose": dose, "marker": marker, "outcome": outcome}})
'''


def rung_6(f):
    header = HEADER.format(seed=POOL_SEED, n=POOL_N)
    return f'''"""Rung 6 - null model: independent marginals of the observational pool.

RATIONALE (rung 5 -> 6): the null keeps only the historical marginals - it
destroys every dependency between columns AND every sensitivity to the regime
(under do(dose) it still samples dose from the pool marginal: the implicit
no-effect claim, priced by the battery on every item). Any fit to real data
beats it on joint structure; it is the calibrated "I know nothing" floor that
anchors the L1 range (S_truth - S_null) and the D_MAX cap semantics.

{header}
"""
import numpy as np
import pandas as pd

MU_DOSE = {f["mu_dose"]!r}
SD_DOSE = {f["sd_dose"]!r}
MU_MARKER = {f["mu_marker"]!r}
SD_MARKER = {f["sd_marker"]!r}
MU_OUTCOME = {f["mu_outcome"]!r}
SD_OUTCOME = {f["sd_outcome"]!r}


def model(regime, n, seed):
    rng = np.random.default_rng(seed)
    dose = np.clip(rng.normal(MU_DOSE, SD_DOSE, n), 0.0, 10.0)
    marker = rng.normal(MU_MARKER, SD_MARKER, n)
    outcome = rng.normal(MU_OUTCOME, SD_OUTCOME, n)
    return pd.DataFrame({{"dose": dose, "marker": marker, "outcome": outcome}})
'''


def write_fixtures(numbers) -> None:
    ladder_dir = CASE_DIR / "ladder"
    ladder_dir.mkdir(exist_ok=True)
    fixtures = {
        "rung_2_perturbed.py": rung_2(numbers),
        "rung_3_linearized.py": rung_3(numbers),
        "rung_4_innocent_twin.py": rung_4(numbers),
        "rung_5_naive_fit.py": rung_5(numbers),
        "rung_6_null.py": rung_6(numbers),
    }
    for name, content in fixtures.items():
        (ladder_dir / name).write_text(content, encoding="utf-8", newline="\n")
        print(f"wrote ladder/{name}")


def calibrate_lambda() -> None:
    """lambda such that lambda * mdl(world.py) = 5% of the NORMALIZATION range
    (fid_truth - fid_naive), the range R maps to [0, 1] (Decision Log v0.12).
    The naive fit (rung 5) is the S_naive anchor; the null is a pathological
    off-support outlier and is NOT a good range basis."""
    from wager.contracts import ScoringParams
    from wager.factory.case_loader import (
        load_battery,
        load_ladder,
        load_meta,
        load_world_sample,
        load_world_source,
    )
    from wager.reward.mdl import mdl_bytes
    from wager.reward.scorer import WorldSide, sandboxed_null_sample, score_submission

    meta = load_meta(CASE_DIR)
    battery = load_battery(CASE_DIR)
    world_sample = load_world_sample(CASE_DIR)
    world_source = load_world_source(CASE_DIR)
    ladder = dict(load_ladder(CASE_DIR))
    naive_code = ladder["rung_5_naive_fit"]
    null_code = ladder["rung_6_null"]
    params = ScoringParams(
        lambda_mdl=0.0,
        n_samples=meta.scoring.n_samples,
        m_reps=meta.scoring.m_reps,
        model_call_timeout_s=meta.scoring.model_call_timeout_s,
    )
    with sandboxed_null_sample(null_code, meta.column_names, params.model_call_timeout_s) as null_sample:
        world_side = WorldSide(
            world_sample, battery, meta.column_names, params.n_samples, null_sample=null_sample
        )
        fid_truth = score_submission(world_source, world_side, params).fidelity
        fid_naive = score_submission(naive_code, world_side, params).fidelity
    fid_range = fid_truth - fid_naive
    lam = 0.05 * fid_range / mdl_bytes(world_source)

    meta_path = CASE_DIR / "meta.json"
    raw = json.loads(meta_path.read_text(encoding="utf-8"))
    raw["scoring"]["lambda_mdl"] = lam
    raw["scoring"]["lambda_provisional"] = True
    meta_path.write_text(json.dumps(raw, indent=2) + "\n", encoding="utf-8", newline="\n")
    print(f"fid_truth={fid_truth:.6f} fid_naive={fid_naive:.6f} norm_range={fid_range:.6f}")
    print(f"lambda_mdl={lam!r} (provisional, =5% of normalization range) -> meta.json")


if __name__ == "__main__":
    pool = observational_pool()
    numbers = fit_numbers(pool)
    write_fixtures(numbers)
    calibrate_lambda()
